# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKapp' do

  use_frameworks!
	pod 'Alamofire', '~> 5.1'
	pod 'Realm'
	pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
	
end
